# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
# Initial code for Github Actions workflow, not yet working as intended
# Last update: 05/29/23 2:39 PM

name: Node.js CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  ssh_setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Ensure SSH is installed on runner
      run: sudo apt-get install openssh-client -y

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh/
        ssh-keyscan -H ${{ secrets.EC2_INSTANCE_HOSTNAMEDNS }} >> ~/.ssh/known_hosts
        cat ~/.ssh/known_hosts
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        echo "$asdtest" > ~/.ssh/test
        cat ~/.ssh/test
        chmod 400 ~/.ssh/id_rsa
        ls -l ~/.ssh/id_rsa

    - name: SSH into EC2 instance
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_INSTANCE_HOSTNAMEDNS }}
        cd /home/ubuntu/

  # build:
  #   needs: ssh_setup
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       node-version: [16.x]

  #   steps:
