# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
# Initial code for Github Actions workflow, not yet working as intended
# Last update: 05/29/23 2:39 PM

name: Node.js CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Ensure SSH is installed on runner
      run: sudo apt-get install openssh-client -y

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh/
        ssh-keyscan -H ${{ secrets.EC2_INSTANCE_HOSTNAMEDNS }} >> ~/.ssh/known_hosts
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 400 ~/.ssh/id_rsa

    - name: SSH into EC2 instance
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_INSTANCE_HOSTNAMEDNS }}

    - name: git pull
      run: git pull

    - name: git checkout to branch
      run: |
        git reset --hard
        git checkout origin/dev

    # - name: build project
    #   run: npm run build

    - name: list running screen sessions
      run: screen -ls

    - name: end running NextJS process
      run: screen -S ${{ secrets.SCREEN_NAME }} -X stuff "^C"